Name: First workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print message
        run: echo "First workflow"
        shell: bash

  bye:
    runs-on: ubuntu-latest
    steps:
      - name: Bye
        run: echo "Completed!!"
        shell: bash


