name: Create a comment on the new issues

on:
    issues:
        types: [opened]

jobs:
    add-comment:
        runs-on: ubuntu-latest
        steps:
            - name: Dump Github context
              run: echo '${{toJson(github.event) }} | jq'
              shell: bash